### PR TITLE
Add a fromEF method for populating transactions from EF hex

### PR DESCRIPTION
**Pull request by sirdeggen**
This creates a fake sourceTransaction and populates everything we know from EF data leaving nulls where we don’t know.

### CODE REVIEW

**Comment by sirdeggen** [comment]
@tiagolr please take a look, tell me what you think. The idea is roughly:

```javascript
import { Transaction, PrivateKey, P2PKH, fromUtxo } from '@bsv.sdk'
const key = PrivateKey.fromWif(env.wif)
const tx = new Transaction()

tx.addInput(fromUtxo({
    txid: '434555433eaca96dff6e71a4d02febd0dd3832e5ca4e5734623ca914522e17d5',
    vout: 0,
    script: '76a914d01b0b702ee90e00944342f97c772a8be83e42a288ac',
    satoshis: 1234
}, new P2PKH().unlock(key)))
```

Under the hoos it will populate a sourceTransaction with the available data - you can even do a `toHexEF()` and it will work.

**Comment by tiagolr** [comment]
Looks great! 
The one limitation I can think of is that Txs cannot compute fee without previous tx again, nonetheless covers my use-case which is to build txs from UTXOs. Maybe you can reason better if this limitation applies to more use cases. 
Regards 
@sirdeggen

**Comment by sirdeggen** [comment]
`tx.getFee()` still works! The data is just kept in a sourceTransaction rather than its own field.

**Comment by tiagolr** [comment]
I know, yet tx.fee() will throw exception if inputs are added without a parent tx, not on my use-case but may be a limitation. Maybe creating placeholder txs is the way to go instead of using source satoshis, leave that to your judgement, the fromUtxo util looks certainly better than [how I'm doing things](https://github.com/bitcoin-sv/ts-sdk/pull/75/files).

**Comment by shruggr** [comment]
What happens if you input is outputIndex 1000. Do you insert 999 nulls in the transaction.outputs?

**Comment by tiagolr** [comment]
Q: Why should the UTXOs based approach be deprecated compared to sourceTxs?

```
 * @deprecated
 * This approach is made available for compatibility only. It is deprecated in favor of using sourceTransactions 
 * directly. It's recommended that wallets general keep transactions which store unspent outputs in their entirety, 
 * along with corresonding Merkle paths. The reason you would keep the whole transaction is such that you can prove 
 * the txid, and therefore its inclusion within a specific block.
 ```
 
 I get the BEEF format and think its amazing however it offers some disadvantages compared to managing UTXOs.

- For data transactions it means storing extra data and sending extra data over the internet compared to UTXOs.
- From my understanding for consecutive TXs it means storing all transactions while they are not inserted into a block, imagine firing 1000 chained txs, it means storing and managing those txs which can be complicated.
- Overall its more complicated to build and manage BEEF txs compared to managing UTXOs.
- Extended Format works well with either utxos or sourceTxs

My only complain is that it seems you're pushing for BEEF format too soon, UTXOs shouldn´t be considered deprecated for compatibility only, at least for now, they are likely the preferred method. Maybe its me that haven´t tried working with sourceTXs and its simpler than it looks although I still think its more complicated than managing UTXOs.

Regards,

**Comment by ty-everett** [comment]
The SPV architecture requires that clients manage this data, because it contributes to the overall scalability of the network. If people don't keep track of their own transactions, they're relying on trusted parties to do so. This doesn't scale from an economic perspective and needs to be discouraged. I was on the fence about the inclusion of these fields, but after further consideration it's extremely important that new applications are strongly encouraged to manage all of their transactions.

It's time we moved away from relying on these old data models as first-class citizens.

**Comment by tiagolr** [comment]
Sounds good, fair point, maybe I am just used to work with UTXOs, no idea how I would manage TXs and BEEF format in my app where I need to fire lots of chained txs and discard txs no longer needed, suppose is just a technical challenge and you already managed that in one of your apps.

**Comment by sirdeggen** [comment]
Chained txs could be supported directly by an Overlay such that you only have to broadcast the last one in a set of 1,000 - when the format is BEEF, which includes all `sourceTransactions`.

There's also an argument to be made for not chaining transactions like this at all. If you have many things to link you can use a hash chain, and spend utxos from a treasury pool of old utxos, so that each tx you broadcast is entirely indepentent.

**Comment by sirdeggen** [comment]
> What happens if you input is outputIndex 1000. Do you insert 999 nulls in the transaction.outputs?

This is a good point. I'm not sure how to solve this one. Opinion softening. Maybe we should allow setting the values directly:

```typescript
tx.addInput({
     // ALLOW 
     sourceTXID,
     sourceSatoshis,
     sourceLockingScript,
     // OR
     sourceTransaction,
     // MUST
     sourceOutputIndex,
     unlockingScriptTemplate
})
```

**Comment by tiagolr** [comment]
> Chained txs could be supported directly by an Overlay such that you only have to broadcast the last one in a set of 1,000 - when the format is BEEF, which includes all `sourceTransactions`.
> 
> There's also an argument to be made for not chaining transactions like this at all. If you have many things to link you can use a hash chain, and spend utxos from a treasury pool of old utxos, so that each tx you broadcast is entirely independent.

Not sure I understand the first point, guess I'll need to wait a bit for the frameworks / processes to mature to understand concrete examples, from my understanding of BEEF format I need to include TXs up to an existing block, that means I need to store and discard txs as they are included in blocks (keeping all TXs is not viable as it means near double the database size).

The second point requires the Utxos to be split beforehand and wait to be included in a block, in my app for example it uses the UTXOs when a payment is made, the app uses those funds to publish sometimes hundreds of TXs right when a channel is funded, hence the hundreds of chained TXs sometimes from a single UTXO.

**Comment by sirdeggen** [comment]
If you need to chain you need to chain, no argument there.

In your case submitting those 100s of transactions together as a single BEEF might improve your experience, but ARC doesn't yet accept that format. Soon™

**Comment by sirdeggen** [comment]
Noting that this PR is pending a conversation with go-sdk development. Looks positive, will merge soon.

**Review by ty-everett — APPROVED** [review]

**Pull request merged**
