### PR TITLE
[feature] add random fee calc benford approx

### PR DESCRIPTION
**Pull request by sirdeggen**
## Description of Changes

Adding Benford approximate random change outputs mode.

## Testing Procedure

Manual testing only. We should add tests to see if it sets change properly for many outputs.

- [x] I have added new unit tests
- [x] All tests pass locally
- [x] I have tested manually in my local environment

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have updated `CHANGELOG.md` with my changes
- [x] I have run `npm run doc` and `npm run lint` one final time before requesting a review
- [x] I have run `npm version patch` so that my changes will trigger a new version to be released when they are merged

### CODE REVIEW

**Comment by sirdeggen** [comment]
I wanted to pause and request @tonesnotes take a look because it's just an approximation. Probably close enough but not truely Benford because of the normalization step. Does that break it?

**Comment by tonesnotes** [comment]
If taken a look through but have not verified the math.

The question I'm asking myself (but haven't answered yet) is whether the change generated by this algorithm wouldn't exhibit its own easily detectable statistical signature. Specifically, Benford's Law generalizes to joint probabilities between first two digits, etc. While this algorithm focuses on the first only (unless I'm miss reading the code).

In my own work on change generation, I've aimed to satisfy requirements for specific numbers of change outputs of specified minimum value. What makes these difficult is acceptable handling of low balance and "too small" limits.

Essentially the requirements are typically over constrained requiring the adoption of acceptable heuristics to resolve conflicts. Maybe there's a neural network in here somewhere...

The capability Craig has long called for is to have multiple generations of change such that a wallet usually isn't spending first generation change: Change generated by a transaction that doesn't just re-arrange change.

**Comment by tonesnotes** [comment]
The ideal amounts for change are actually the identical amounts used for non-change. A wallet could maintain the history of recently used non-change amounts and select change values from there. Effectively this outsources Benford's Law to the wallets day-to-day transaction values.

**Comment by sirdeggen** [comment]
Definitely think that the number of inputs added and change outputs appended ought to be considered in wallet design at a higher level. Really what we're talking about here is sprinkling a fixed remainder across outputs set to change: true as a more-obfuscation-than-all-equal algo. 

Open to PRs which propose a better alternative. This is now "fixed" in that it has a scheme designed to avoid the problem which arises when you have 13 sats to distribute across 8 change outputs - where most are just 1, and one or two have 2 for example.

**Review by ty-everett — APPROVED** [review]

**Pull request merged**
